spring.application.name=DigitalAssetLendingSystem
server.port=9000
spring.datasource.url=jdbc:mysql://localhost:3306/digital_asset?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Siri@22032004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true